In [1]:
import glob
import time
import os
import jpeg4py as jpeg
from PIL import Image
import struct
import imghdr
import skimage.io
import imageio
import cv2
import shutil
import numpy as np
from io import BytesIO
from turbojpeg import TurboJPEG, TJPF_GRAY, TJSAMP_GRAY, TJFLAG_PROGRESSIVE

In [2]:
# graphwiz path variable
os.environ["PATH"] += os.pathsep + "C:\\libjpeg-turbo-gcc64\\bin\\libturbojpeg.dll"

In [3]:
os.environ["path"].split(os.pathsep)

['d:\\jupyter_notebook\\virtualenv_keras\\keras\\lib\\site-packages\\pywin32_system32',
 'd:\\jupyter_notebook\\virtualenv_keras\\keras\\lib\\site-packages\\pywin32_system32',
 'd:\\jupyter_notebook\\virtualenv_keras\\keras\\lib\\site-packages\\pywin32_system32',
 'D:\\jupyter_notebook\\virtualenv_keras\\keras\\Scripts',
 'C:\\Users\\Ridzuan\\bin',
 'C:\\Program Files\\Git\\mingw64\\bin',
 'C:\\Program Files\\Git\\usr\\local\\bin',
 'C:\\Program Files\\Git\\usr\\bin',
 'C:\\Program Files\\Git\\usr\\bin',
 'C:\\Program Files\\Git\\mingw64\\bin',
 'C:\\Program Files\\Git\\usr\\bin',
 'C:\\Users\\Ridzuan\\bin',
 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common',
 'C:\\Program Files\\Python36\\Scripts',
 'C:\\Program Files\\Python36',
 'C:\\Program Files (x86)\\Python37-32\\Scripts',
 'C:\\Program Files (x86)\\Python37-32',
 'C:\\Python\\Python36\\Scripts',
 'C:\\Python\\Python36',
 'C:\\Python\\Python37-32\\Scripts',
 'C:\\Python\\Python37-32',
 'C:\\Program Files (x86)\\Razer 

In [2]:
INPUT_PATH_PNG = "../datasets/iwildcam-2019-fgvc6/train_images/"
files_png_init = sorted(glob.glob(INPUT_PATH_PNG + '*.jpg'))
len(files_png_init)

196086

In [28]:
files_png_init[0]

'../datasets/iwildcam-2019-fgvc6/train_images\\5858bf1e-23d2-11e8-a6a3-ec086b02610b.jpg'

In [9]:
start_time = time.time()
d = []
for f in files_png_init[0:10000]:
    a = jpeg.JPEG(f).decode()
    d.append(a)
print('Time to read {} JPEGs small for libjpeg-turbo (jpeg4py): {:.2f} sec'.format(len(files_png_init[0:10000]), time.time() - start_time))

Time to read 10000 JPEGs small for libjpeg-turbo (jpeg4py): 856.41 sec


In [19]:
x = TurboJPEG("C:\\libjpeg-turbo-gcc64\\bin\\libturbojpeg.dll")

In [42]:
start_time_1 = time.time()
for i in range(30):
   image = jpeg.JPEG(files_png_init[0]).decode()
   image = tf.constant(image)
print(time.time() - start_time_1)
image

0.15199851989746094


<tf.Tensor: shape=(747, 1024, 3), dtype=uint8, numpy=
array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[129, 110,  68],
        [158, 139,  96],
        [156, 137,  94],
        ...,
        [100,  93,  49],
        [ 91, 104,  50],
        [ 90, 111,  52]],

       [[143, 123,  73],
        [173, 153, 102],
        [172, 150, 100],
        ...,
        [139, 133,  85],
        [133, 147,  86],
        [132, 154,  89]],

       [[160, 139,  84],
        [188, 167, 110],
        [184, 162, 105],
        ...,
        [139, 132,  

In [41]:
import tensorflow as tf

start_time_2 = time.time()
for i in range(30):
   image = tf.image.decode_jpeg(tf.io.read_file(files_png_init[i]), channels = 3)
print(time.time()-start_time_2)
image

1.0640640258789062


<tf.Tensor: shape=(747, 1024, 3), dtype=uint8, numpy=
array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ...,

       [[19, 29, 18],
        [18, 28, 17],
        [19, 29, 18],
        ...,
        [31, 46, 43],
        [30, 47, 41],
        [30, 47, 41]],

       [[20, 30, 19],
        [19, 29, 18],
        [20, 30, 19],
        ...,
        [31, 46, 43],
        [30, 47, 41],
        [30, 47, 41]],

       [[21, 31, 20],
        [21, 31, 20],
        [21, 31, 20],
        ...,
        [31, 46, 43],
        [30, 47, 41],
        [30, 47, 41]]], dtype=uint8)>